### ISSUE TITLE
Swift SDK

### ISSUE THREAD

**Issue by dimohamdy** [RedBearLab/iOS#25]
Did Swift SKD ready to use ?
did "didUpdateValueForCharacteristic" method implementation in swift finished ?

did we need to  chunk date  when receive like objc ?

Objc [link](https://github.com/RedBearLab/iOS/blob/51a1c6912a62ffef0cf514db04ad98a303f036f8/Examples/BLE%20Select/BLE/BLE.m#L517)

Swift [link](https://github.com/RedBearLab/iOS/blob/b687b1a4cde7973f7cc59422946c18ed157859a5/BLEFramework/BLE/BLE.swift#L238)

**Comment by dimohamdy** [comment]
@Cheong2K any update

**Comment by Cheong2K** [comment]
Hi, sorry, the swift code was contributed by other developers, I only support objective-c, do you have any problems when using it?

**Comment by dimohamdy** [comment]
@Cheong2K  i want to ask is this finished or still beta 
@kouky  please help me

**Comment by kouky** [comment]
@dimohamdy the CoreBluetooth peripheral delegate method `didUpdateValueForCharacteristic` is definitely called by the swift SDK. I used that delegate method and the swift SDK in a recent project, the full write up in on my blog.
http://kouky.org/blog/2016/04/09/mavlink-radio-telemetry-for-ios.html
